# Generated by Django 6.0.2 on 2026-02-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_country_property_property_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
