# Generated by Django 6.0.2 on 2026-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_property_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='external_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
