# Generated by Django 6.0.2 on 2026-02-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_property_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
